---
stages:
  - init
  - test
  - gen
  - build
  - ostree-gen
  - ostree-build
  - verify
  - finish

variables:
  # Set the parent pipeline ID as a global variable so that the child pipeline
  # jobs can use it to retrieve artifacts.
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  GOPROXY: "https://proxy.golang.org,direct"

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish

fail:
  stage: finish
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh fail
    - exit 1  # make the pipeline fail so it doesn't look like success
  when: on_failure

.base:
  before_script:
    - cat schutzbot/team_ssh_keys.txt |
        tee -a ~/.ssh/authorized_keys > /dev/null
  interruptible: true
  retry: 1
  tags:
    - terraform
  variables:
    PYTHONUNBUFFERED: 1

.terraform:
  extends: .base
  tags:
    - terraform

"bootc-image-builder/test/test_build_pxe.py [x86_64]":
  stage: test
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64-kvm
  rules:
    # 1. Skip the job if we're on the github merge queue
    - if: '$CI_COMMIT_BRANCH =~ /^gh-readonly-queue/'
      when: never
    # 2. Fallback rule for any other branch name
    - if: '$CI_COMMIT_BRANCH'
  script:
    - sudo ./test/scripts/install-dependencies
    - sudo mkdir -pv /var/tmp/bootc-image-builder-tests
    - sudo -E XDG_RUNTIME_DIR= PYTHONPATH=. pytest -vv --basetemp=/var/tmp/bootc-image-builder-tests bootc-image-builder/test/test_build_pxe.py
  needs:
    - init


"bootc-image-builder/test/test_build_pxe.py [aarch64]":
  stage: test
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
  rules:
    # 1. Skip the job if we're on the github merge queue
    - if: '$CI_COMMIT_BRANCH =~ /^gh-readonly-queue/'
      when: never
    # 2. Fallback rule for any other branch name
    - if: '$CI_COMMIT_BRANCH'
  script:
    - sudo ./test/scripts/install-dependencies
    - sudo mkdir -pv /var/tmp/bootc-image-builder-tests
    - sudo -E XDG_RUNTIME_DIR= PYTHONPATH=. pytest -vv --basetemp=/var/tmp/bootc-image-builder-tests bootc-image-builder/test/test_build_pxe.py
  needs:
    - init
