---
stages:
  - init
  - build
  - ostree-build
  - finish

variables:
  GOPROXY: "https://proxy.golang.org,direct"

.base:
  before_script:
    - cat schutzbot/team_ssh_keys.txt |
        tee -a ~/.ssh/authorized_keys > /dev/null
  interruptible: true
  retry: 1
  tags:
    - terraform
  variables:
    PYTHONUNBUFFERED: 1

.terraform:
  extends: .base
  tags:
    - terraform

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish

fail:
  stage: finish
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh fail
    - exit 1  # make the pipeline fail so it doesn't look like success
  when: on_failure

"test-images: [centos-10, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro centos-10 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [centos-10, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro centos-10 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [centos-9, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro centos-9 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [centos-9, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro centos-9 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [eln-11, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro eln-11 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [eln-11, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro eln-11 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [fedora-43, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro fedora-43 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [fedora-43, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro fedora-43 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [fedora-44, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro fedora-44 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [fedora-44, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro fedora-44 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [fedora-45, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro fedora-45 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [fedora-45, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro fedora-45 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-10.0, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-10.0 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-10.0, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-10.0 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-10.1, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-10.1 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-10.1, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-10.1 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-10.2, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-10.2 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-10.2, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-10.2 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-10.3, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-10.3 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-10.3, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-10.3 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-7.9, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/centos-stream-9-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-7.9 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-8.10, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-8.10 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-8.10, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-8.10 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-8.4, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-8.4 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-8.4, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-8.4 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-8.6, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-8.6 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-8.6, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-8.6 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-8.8, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-8.8 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-8.8, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-8.8 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.0, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.0 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.0, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.0 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.2, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.2 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.2, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.2 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.4, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.4 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.4, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.4 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.6, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.6 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.6, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.6 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.7, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.7 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.7, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.7 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.8, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.8 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.8, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.8 --arch x86_64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.9, aarch64]":
  stage: build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.9 --arch aarch64
  artifacts:
    paths:
      - ./logs


"test-images: [rhel-9.9, x86_64]":
  stage: build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro rhel-9.9 --arch x86_64
  artifacts:
    paths:
      - ./logs

"test-ostree-images: [centos-9, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro centos-9 --arch aarch64
  needs:
    - "test-images: [centos-9, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [centos-9, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro centos-9 --arch x86_64
  needs:
    - "test-images: [centos-9, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [fedora-43, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro fedora-43 --arch aarch64
  needs:
    - "test-images: [fedora-43, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [fedora-43, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro fedora-43 --arch x86_64
  needs:
    - "test-images: [fedora-43, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [fedora-44, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro fedora-44 --arch aarch64
  needs:
    - "test-images: [fedora-44, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [fedora-44, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro fedora-44 --arch x86_64
  needs:
    - "test-images: [fedora-44, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [fedora-45, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro fedora-45 --arch aarch64
  needs:
    - "test-images: [fedora-45, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [fedora-45, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro fedora-45 --arch x86_64
  needs:
    - "test-images: [fedora-45, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-8.10, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-8.10 --arch aarch64
  needs:
    - "test-images: [rhel-8.10, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-8.10, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-8.10 --arch x86_64
  needs:
    - "test-images: [rhel-8.10, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-8.4, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-8.4 --arch aarch64
  needs:
    - "test-images: [rhel-8.4, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-8.4, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-8.4 --arch x86_64
  needs:
    - "test-images: [rhel-8.4, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-8.6, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-8.6 --arch aarch64
  needs:
    - "test-images: [rhel-8.6, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-8.6, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-8.6 --arch x86_64
  needs:
    - "test-images: [rhel-8.6, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-8.8, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-8.8 --arch aarch64
  needs:
    - "test-images: [rhel-8.8, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-8.8, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-8.8 --arch x86_64
  needs:
    - "test-images: [rhel-8.8, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.0, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.0 --arch aarch64
  needs:
    - "test-images: [rhel-9.0, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.0, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.0 --arch x86_64
  needs:
    - "test-images: [rhel-9.0, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.2, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.2 --arch aarch64
  needs:
    - "test-images: [rhel-9.2, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.2, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.2 --arch x86_64
  needs:
    - "test-images: [rhel-9.2, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.4, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.4 --arch aarch64
  needs:
    - "test-images: [rhel-9.4, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.4, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.4 --arch x86_64
  needs:
    - "test-images: [rhel-9.4, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.6, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.6 --arch aarch64
  needs:
    - "test-images: [rhel-9.6, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.6, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.6 --arch x86_64
  needs:
    - "test-images: [rhel-9.6, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.7, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.7 --arch aarch64
  needs:
    - "test-images: [rhel-9.7, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.7, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.7 --arch x86_64
  needs:
    - "test-images: [rhel-9.7, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.8, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.8 --arch aarch64
  needs:
    - "test-images: [rhel-9.8, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.8, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.8 --arch x86_64
  needs:
    - "test-images: [rhel-9.8, x86_64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.9, aarch64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform
  variables:
    RUNNER: aws/fedora-44-aarch64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.9 --arch aarch64
  needs:
    - "test-images: [rhel-9.9, aarch64]"
  artifacts:
    paths:
      - ./logs


"test-ostree-images: [rhel-9.9, x86_64]":
  stage: ostree-build
  extends: .terraform
  tags:
    - terraform/openstack
  variables:
    RUNNER: rhos-01/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro rhel-9.9 --arch x86_64
  needs:
    - "test-images: [rhel-9.9, x86_64]"
  artifacts:
    paths:
      - ./logs

"generate-manifests: [centos-10, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros centos-10 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [centos-10, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros centos-10 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [centos-9, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros centos-9 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [centos-9, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros centos-9 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [eln-11, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros eln-11 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [eln-11, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros eln-11 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [fedora-43, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros fedora-43 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [fedora-43, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros fedora-43 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [fedora-44, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros fedora-44 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [fedora-44, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros fedora-44 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [fedora-45, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros fedora-45 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [fedora-45, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros fedora-45 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-10.0, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-10.0 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-10.0, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-10.0 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-10.1, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-10.1 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-10.1, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-10.1 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-10.2, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-10.2 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-10.2, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-10.2 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-10.3, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-10.3 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-10.3, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-10.3 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-8.10, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-8.10 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-8.10, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-8.10 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-8.4, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-8.4 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-8.4, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-8.4 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-8.6, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-8.6 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-8.6, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-8.6 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-8.8, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-8.8 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-8.8, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-8.8 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.0, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-9.0 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.0, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-9.0 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.2, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-9.2 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.2, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-9.2 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.4, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-9.4 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.4, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-9.4 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.6, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-9.6 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.6, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-9.6 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.7, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-9.7 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.7, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-9.7 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.8, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-9.8 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.8, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-9.8 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.9, ppc64le]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches ppc64le --distros rhel-9.9 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"


"generate-manifests: [rhel-9.9, s390x]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: aws/fedora-44-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches s390x --distros rhel-9.9 --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"
