coverage:
  status:
    patch: no
    project:
      default:
        threshold: 5%
codecov:
  require_ci_to_pass: no
comment:
    behavior: new
    layout: "condensed_header, files, condensed_footer"
    hide_project_coverage: TRUE

