pipeline {
    agent none

    options {
        timestamps()
        ansiColor('xterm')
        // Cancel the pipeline if it runs for more than 30 minutes.
        timeout(
            time: 30,
            unit: "MINUTES"
        )
    }

    stages {
        stage("Prepare 🤔") {
            agent { label "schutzbot" }
            options {
                // Don't checkout the git repository here. It just clogs
                // up the Jenkins disk space and does nothing for us.
                skipDefaultCheckout()
            }
            steps {
                sh (
                    label: "Get environment variables",
                    script: "env | sort"
                )
            }
        }

        stage("Test ✅") {
            parallel {
                stage('F32') {
                    agent { label "f32cloudbase && x86_64 && aws" }
                    steps {
                        sh "schutzbot/ci_details.sh"
                        sh "schutzbot/build.sh"
                        sh "schutzbot/provision-composer.sh"
                        sh "schutzbot/run_tests.sh"
                    }
                }
                stage('EL8') {
                    agent { label "rhel8cloudbase && x86_64 && aws" }
                    environment {
                        RHN_REGISTRATION_SCRIPT = credentials('rhn-register-script-production')
                    }
                    steps {
                        sh "schutzbot/ci_details.sh"
                        sh "schutzbot/build.sh"
                        sh "schutzbot/provision-composer.sh"
                        sh "schutzbot/run_tests.sh"
                    }
                }
            }
        }
    }
}
