// Package recommendations provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package recommendations

// GetModelVersion200Response defines model for GetModelVersion200Response.
type GetModelVersion200Response struct {
	Version *string `json:"version,omitempty"`
}

// RecommendPackageRequest defines model for RecommendPackageRequest.
type RecommendPackageRequest struct {
	Packages            []string `json:"packages"`
	RecommendedPackages int32    `json:"recommendedPackages"`
}

// RecommendationsResponse defines model for RecommendationsResponse.
type RecommendationsResponse struct {
	Packages []string `json:"packages"`
}

// RefreshModel200Response defines model for RefreshModel200Response.
type RefreshModel200Response struct {
	Message *string `json:"message,omitempty"`
}

// GetRecommendedPackagesJSONRequestBody defines body for GetRecommendedPackages for application/json ContentType.
type GetRecommendedPackagesJSONRequestBody = RecommendPackageRequest
