---
openapi: 3.0.1
info:
  version: "1"
  title: Osbuild-installer service
  description: Service that relays image build requests
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /version:
    get:
      summary: get the service version
      description: "get the service version"
      operationId: getVersion
      responses:
        '200':
          description: a service version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'

  /openapi.json:
    get:
      summary: get the openapi json specification
      operationId: getOpenapiJson
      tags:
        - meta
      responses:
        '200':
          description: returns this document

  /compose/{composeId}:
    get:
      summary: get status of an image compose
      parameters:
        - in: path
          name: composeId
          schema:
            type: string
          required: true
          description: Id of compose status to get
      description: "status of an image compose"
      operationId: getComposeStatus
      responses:
        '200':
          description: compose status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComposeStatus'

  /compose:
    post:
      summary: compose image
      description: "compose image"
      operationId: composeImage
      requestBody:
        required: true
        description: details of image to be composed
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ComposeRequest"
      responses:
        '200':
          description: compose has started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComposeResponse'

components:
  schemas:
    Version:
      required:
        - version
      properties:
        version:
          type: string
    ComposeStatus:
      required:
        - status
      properties:
        status:
          type: string
    ComposeRequest:
      type: object
      required:
        - image_builds
      properties:
        image_builds:
          type:
            array
          items:
            $ref: '#/components/schemas/Compose'
    Compose:
      required:
        - distribution
        - architecture
        - image_type
        - repositories
      properties:
        distribution:
          type: string
        architecture:
          type: string
        image_type:
          type: string
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/Repository'
    Repository:
      type: object
      required:
        - baseurl
      properties:
        baseurl:
          type: string
    ComposeResponse:
      required:
        - compose_id
      properties:
        compose_id:
          type: string
