{
 "title": "Image Builder CRC",
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "5m,30m,1h,6h,12h,1d,3d,7d,14d,28d"
   },
   { "name": "stability_slo", "query": "0.95" },
   { "name": "compose_latency_slo", "query": "0.9" },
   { "name": "noncompose_latency_slo", "query": "0.9" }
  ]
 },
 "panels": [
  { "title": "SLO Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compose Success Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(rate(image_builder_crc_compose_errors[$__range])) / sum(rate(image_builder_crc_compose_requests_total[$__range]))"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(rate(api_3scale_gateway_api_status{exported_service=\"image-builder\",status=\"5xx\"}[$__range])) / sum(rate(api_3scale_gateway_api_status{exported_service=\"image-builder\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Compose Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_builder_crc_compose_requests_total[$__range]))"
    }
   ]
  },
  {
   "title": "Current Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"image-builder\"})"
    }
   ]
  },
  {
   "title": "Compose Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(image_builder_crc_http_duration_seconds_bucket{path=~\".*compose\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Non-compose Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(image_builder_crc_http_duration_seconds_bucket{path!~\".*compose\"}[$__range])) by (le)) * 1000"
    }
   ]
  },
  { "title": "Compose Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Compose Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(image_builder_crc_compose_errors[$__range]))/sum(increase(image_builder_crc_compose_requests_total[$__range]))"
    }
   ]
  },
  {
   "title": "Compose Error Budget Remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * (1 - $stability_slo) / ((sum(rate(image_builder_crc_compose_errors[$__range]))/ sum(rate(image_builder_crc_compose_requests_total[$__range]))) + 0.001)"
    }
   ]
  },
  {
   "title": "Compose Error Budget Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((1 - sum(increase(image_builder_crc_compose_errors[$__range]))/sum(increase(image_builder_crc_compose_requests_total[$__range]))) - $stability_slo)/ (1 - $stability_slo)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "Compose Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Compose request response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(image_builder_crc_http_duration_seconds_bucket{path=~\".*compose\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Compose Latency Error Budget Remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * (1 - $compose_latency_slo) / (1 - sum(rate(image_builder_crc_http_duration_seconds_bucket{le=\"12\",path=~\".*compose\"}[$__range]))/sum(rate(image_builder_crc_http_duration_seconds_count{path=~\".*compose\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Compose Latency Error Budget Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum(increase(image_builder_crc_http_duration_seconds_bucket{le=\"12\",path=~\".*compose\"}[$__range]))/sum(increase(image_builder_crc_http_duration_seconds_count{path=~\".*compose\"}[$__range]))) - $compose_latency_slo)/ (1 - $compose_latency_slo)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "Non-Compose Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Non-compose request response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(image_builder_crc_http_duration_seconds_bucket{path!~\".*compose\"}[$__range]))) * 1000"
    }
   ]
  },
  {
   "title": "Non-Compose Latency Error Budget Remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * (1 - $noncompose_latency_slo) / (1 - sum(rate(image_builder_crc_http_duration_seconds_bucket{le=\"0.2\",path!~\".*compose\"}[$__range]))/sum(rate(image_builder_crc_http_duration_seconds_count{path!~\".*compose\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Non-Compose Latency Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum(increase(image_builder_crc_http_duration_seconds_bucket{le=\"0.2\",path!~\".*compose\"}[$__range]))/sum(increase(image_builder_crc_http_duration_seconds_count{path!~\".*compose\"}[$__range]))) - $noncompose_latency_slo)/ (1 - $noncompose_latency_slo)",
     "legendFormat": "errorbudget"
    }
   ]
  }
 ]
}