// Package recommendations provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package recommendations

// GetModel200Response defines model for GetModel200Response.
type GetModel200Response struct {
	Version *string `json:"version,omitempty"`
}

// Response defines model for Response.
type Response struct {
	Message *string `json:"message,omitempty"`
}

// UploadPackageRequest defines model for UploadPackageRequest.
type UploadPackageRequest struct {
	Packages            *[]string `json:"packages,omitempty"`
	RecommendedPackages *int32    `json:"recommendedPackages,omitempty"`
}

// UploadPackageJSONRequestBody defines body for UploadPackage for application/json ContentType.
type UploadPackageJSONRequestBody = UploadPackageRequest
