---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
tags:
- name: recommendations
  description: the recommendations API
paths:
  "/api/packages/recommendations":
    post:
      tags:
      - recommendations
      summary: List recommended packages.
      description: Returns a list of recommended packages for given list of packages.
      operationId: uploadPackage
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UploadPackageRequest"
        required: true
      responses:
        '200':
          description: Return the recommended packages.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Response"
  "/api/models/version":
    get:
      tags:
      - recommendations
      summary: Get model version
      description: Retrieves the model version details.
      operationId: getModel
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetModel200Response"
components:
  schemas:
    Response:
      type: object
      properties:
        message:
          type: string
    UploadPackageRequest:
      type: object
      properties:
        packages:
          type: array
          items:
            type: string
        recommendedPackages:
          type: integer
          format: int32
    GetModel200Response:
      type: object
      properties:
        version:
          type: string
