// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for Distributions.
const (
	Centos8 Distributions = "centos-8"
	Centos9 Distributions = "centos-9"
	Rhel8   Distributions = "rhel-8"
	Rhel84  Distributions = "rhel-84"
	Rhel85  Distributions = "rhel-85"
	Rhel86  Distributions = "rhel-86"
	Rhel9   Distributions = "rhel-9"
	Rhel90  Distributions = "rhel-90"
)

// Defines values for ImageRequestArchitecture.
const (
	X8664 ImageRequestArchitecture = "x86_64"
)

// Defines values for ImageStatusStatus.
const (
	ImageStatusStatusBuilding    ImageStatusStatus = "building"
	ImageStatusStatusFailure     ImageStatusStatus = "failure"
	ImageStatusStatusPending     ImageStatusStatus = "pending"
	ImageStatusStatusRegistering ImageStatusStatus = "registering"
	ImageStatusStatusSuccess     ImageStatusStatus = "success"
	ImageStatusStatusUploading   ImageStatusStatus = "uploading"
)

// Defines values for ImageTypes.
const (
	ImageTypesAmi               ImageTypes = "ami"
	ImageTypesAws               ImageTypes = "aws"
	ImageTypesAzure             ImageTypes = "azure"
	ImageTypesEdgeCommit        ImageTypes = "edge-commit"
	ImageTypesEdgeInstaller     ImageTypes = "edge-installer"
	ImageTypesGcp               ImageTypes = "gcp"
	ImageTypesGuestImage        ImageTypes = "guest-image"
	ImageTypesImageInstaller    ImageTypes = "image-installer"
	ImageTypesRhelEdgeCommit    ImageTypes = "rhel-edge-commit"
	ImageTypesRhelEdgeInstaller ImageTypes = "rhel-edge-installer"
	ImageTypesVhd               ImageTypes = "vhd"
	ImageTypesVsphere           ImageTypes = "vsphere"
)

// Defines values for UploadStatusStatus.
const (
	UploadStatusStatusFailure UploadStatusStatus = "failure"
	UploadStatusStatusPending UploadStatusStatus = "pending"
	UploadStatusStatusRunning UploadStatusStatus = "running"
	UploadStatusStatusSuccess UploadStatusStatus = "success"
)

// Defines values for UploadTypes.
const (
	UploadTypesAws   UploadTypes = "aws"
	UploadTypesAwsS3 UploadTypes = "aws.s3"
	UploadTypesAzure UploadTypes = "azure"
	UploadTypesGcp   UploadTypes = "gcp"
)

// AWSS3UploadRequestOptions defines model for AWSS3UploadRequestOptions.
type AWSS3UploadRequestOptions = map[string]interface{}

// AWSS3UploadStatus defines model for AWSS3UploadStatus.
type AWSS3UploadStatus struct {
	Url string `json:"url"`
}

// AWSUploadRequestOptions defines model for AWSUploadRequestOptions.
type AWSUploadRequestOptions struct {
	ShareWithAccounts []string `json:"share_with_accounts"`
}

// AWSUploadStatus defines model for AWSUploadStatus.
type AWSUploadStatus struct {
	Ami    string `json:"ami"`
	Region string `json:"region"`
}

// ArchitectureItem defines model for ArchitectureItem.
type ArchitectureItem struct {
	Arch       string   `json:"arch"`
	ImageTypes []string `json:"image_types"`
}

// Architectures defines model for Architectures.
type Architectures = []ArchitectureItem

// AzureUploadRequestOptions defines model for AzureUploadRequestOptions.
type AzureUploadRequestOptions struct {
	// Name of the resource group where the image should be uploaded.
	ResourceGroup string `json:"resource_group"`

	// ID of subscription where the image should be uploaded.
	SubscriptionId string `json:"subscription_id"`

	// ID of the tenant where the image should be uploaded. This link explains how
	// to find it in the Azure Portal:
	// https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
	TenantId string `json:"tenant_id"`
}

// AzureUploadStatus defines model for AzureUploadStatus.
type AzureUploadStatus struct {
	ImageName string `json:"image_name"`
}

// ComposeMetadata defines model for ComposeMetadata.
type ComposeMetadata struct {
	// ID (hash) of the built commit
	OstreeCommit *string `json:"ostree_commit,omitempty"`

	// Package list including NEVRA
	Packages *[]PackageMetadata `json:"packages,omitempty"`
}

// ComposeRequest defines model for ComposeRequest.
type ComposeRequest struct {
	Customizations *Customizations `json:"customizations,omitempty"`
	Distribution   Distributions   `json:"distribution"`
	ImageName      *string         `json:"image_name,omitempty"`

	// Array of exactly one image request. Having more image requests in one compose is currently not supported.
	ImageRequests []ImageRequest `json:"image_requests"`
}

// ComposeResponse defines model for ComposeResponse.
type ComposeResponse struct {
	Id string `json:"id"`
}

// ComposeStatus defines model for ComposeStatus.
type ComposeStatus struct {
	ImageStatus ImageStatus `json:"image_status"`
}

// ComposeStatusError defines model for ComposeStatusError.
type ComposeStatusError struct {
	Details *interface{} `json:"details,omitempty"`
	Id      int          `json:"id"`
	Reason  string       `json:"reason"`
}

// ComposesResponse defines model for ComposesResponse.
type ComposesResponse struct {
	Data  []ComposesResponseItem `json:"data"`
	Links struct {
		First string `json:"first"`
		Last  string `json:"last"`
	} `json:"links"`
	Meta struct {
		Count int `json:"count"`
	} `json:"meta"`
}

// ComposesResponseItem defines model for ComposesResponseItem.
type ComposesResponseItem struct {
	CreatedAt string      `json:"created_at"`
	Id        string      `json:"id"`
	ImageName *string     `json:"image_name,omitempty"`
	Request   interface{} `json:"request"`
}

// Customizations defines model for Customizations.
type Customizations struct {
	Filesystem          *[]Filesystem `json:"filesystem,omitempty"`
	Packages            *[]string     `json:"packages,omitempty"`
	PayloadRepositories *[]Repository `json:"payload_repositories,omitempty"`
	Subscription        *Subscription `json:"subscription,omitempty"`

	// list of users that a customer can add, also specifying their respective groups and SSH keys
	Users *[]User `json:"users,omitempty"`
}

// DistributionItem defines model for DistributionItem.
type DistributionItem struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// Distributions defines model for Distributions.
type Distributions string

// DistributionsResponse defines model for DistributionsResponse.
type DistributionsResponse = []DistributionItem

// Filesystem defines model for Filesystem.
type Filesystem struct {
	MinSize    uint64 `json:"min_size"`
	Mountpoint string `json:"mountpoint"`
}

// GCPUploadRequestOptions defines model for GCPUploadRequestOptions.
type GCPUploadRequestOptions struct {
	// List of valid Google accounts to share the imported Compute Node image with.
	// Each string must contain a specifier of the account type. Valid formats are:
	//   - 'user:{emailid}': An email address that represents a specific
	//     Google account. For example, 'alice@example.com'.
	//   - 'serviceAccount:{emailid}': An email address that represents a
	//     service account. For example, 'my-other-app@appspot.gserviceaccount.com'.
	//   - 'group:{emailid}': An email address that represents a Google group.
	//     For example, 'admins@example.com'.
	//   - 'domain:{domain}': The G Suite domain (primary) that represents all
	//     the users of that domain. For example, 'google.com' or 'example.com'.
	//     If not specified, the imported Compute Node image is not shared with any
	//     account.
	ShareWithAccounts []string `json:"share_with_accounts"`
}

// GCPUploadStatus defines model for GCPUploadStatus.
type GCPUploadStatus struct {
	ImageName string `json:"image_name"`
	ProjectId string `json:"project_id"`
}

// HTTPError defines model for HTTPError.
type HTTPError struct {
	Detail string `json:"detail"`
	Title  string `json:"title"`
}

// HTTPErrorList defines model for HTTPErrorList.
type HTTPErrorList struct {
	Errors []HTTPError `json:"errors"`
}

// ImageRequest defines model for ImageRequest.
type ImageRequest struct {
	// CPU architecture of the image, only x86_64 is currently supported.
	Architecture  ImageRequestArchitecture `json:"architecture"`
	ImageType     ImageTypes               `json:"image_type"`
	Ostree        *OSTree                  `json:"ostree,omitempty"`
	UploadRequest *UploadRequest           `json:"upload_request,omitempty"`
}

// CPU architecture of the image, only x86_64 is currently supported.
type ImageRequestArchitecture string

// ImageStatus defines model for ImageStatus.
type ImageStatus struct {
	Error        *ComposeStatusError `json:"error,omitempty"`
	Status       ImageStatusStatus   `json:"status"`
	UploadStatus *UploadStatus       `json:"upload_status,omitempty"`
}

// ImageStatusStatus defines model for ImageStatus.Status.
type ImageStatusStatus string

// ImageTypes defines model for ImageTypes.
type ImageTypes string

// OSTree defines model for OSTree.
type OSTree struct {
	// Can be either a commit (example: 02604b2da6e954bd34b8b82a835e5a77d2b60ffa), or a branch-like reference (example: rhel/8/x86_64/edge)
	Parent *string `json:"parent,omitempty"`
	Ref    *string `json:"ref,omitempty"`
	Url    *string `json:"url,omitempty"`
}

// Package defines model for Package.
type Package struct {
	Name    string `json:"name"`
	Summary string `json:"summary"`
}

// PackageMetadata defines model for PackageMetadata.
type PackageMetadata struct {
	Arch      string  `json:"arch"`
	Epoch     *string `json:"epoch,omitempty"`
	Name      string  `json:"name"`
	Release   string  `json:"release"`
	Sigmd5    string  `json:"sigmd5"`
	Signature *string `json:"signature,omitempty"`
	Type      string  `json:"type"`
	Version   string  `json:"version"`
}

// PackagesResponse defines model for PackagesResponse.
type PackagesResponse struct {
	Data  []Package `json:"data"`
	Links struct {
		First string `json:"first"`
		Last  string `json:"last"`
	} `json:"links"`
	Meta struct {
		Count int `json:"count"`
	} `json:"meta"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Readiness string `json:"readiness"`
}

// Repository defines model for Repository.
type Repository struct {
	Baseurl    *string `json:"baseurl,omitempty"`
	CheckGpg   *bool   `json:"check_gpg,omitempty"`
	Gpgkey     *string `json:"gpgkey,omitempty"`
	IgnoreSsl  *bool   `json:"ignore_ssl,omitempty"`
	Metalink   *string `json:"metalink,omitempty"`
	Mirrorlist *string `json:"mirrorlist,omitempty"`
	Rhsm       bool    `json:"rhsm"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	ActivationKey string `json:"activation-key"`
	BaseUrl       string `json:"base-url"`
	Insights      bool   `json:"insights"`
	Organization  int    `json:"organization"`
	ServerUrl     string `json:"server-url"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	Options interface{} `json:"options"`
	Type    UploadTypes `json:"type"`
}

// UploadStatus defines model for UploadStatus.
type UploadStatus struct {
	Options interface{}        `json:"options"`
	Status  UploadStatusStatus `json:"status"`
	Type    UploadTypes        `json:"type"`
}

// UploadStatusStatus defines model for UploadStatus.Status.
type UploadStatusStatus string

// UploadTypes defines model for UploadTypes.
type UploadTypes string

// User defines model for User.
type User struct {
	Name   string `json:"name"`
	SshKey string `json:"ssh_key"`
}

// Version defines model for Version.
type Version struct {
	Version string `json:"version"`
}

// ComposeImageJSONBody defines parameters for ComposeImage.
type ComposeImageJSONBody = ComposeRequest

// GetComposesParams defines parameters for GetComposes.
type GetComposesParams struct {
	// max amount of composes, default 100
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// composes page offset, default 0
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetPackagesParams defines parameters for GetPackages.
type GetPackagesParams struct {
	// distribution to look up packages for
	Distribution Distributions `form:"distribution" json:"distribution"`

	// architecture to look up packages for
	Architecture GetPackagesParamsArchitecture `form:"architecture" json:"architecture"`

	// packages to look for
	Search string `form:"search" json:"search"`

	// max amount of packages, default 100
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// packages page offset, default 0
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetPackagesParamsArchitecture defines parameters for GetPackages.
type GetPackagesParamsArchitecture string

// ComposeImageJSONRequestBody defines body for ComposeImage for application/json ContentType.
type ComposeImageJSONRequestBody = ComposeImageJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// get the architectures and their image types available for a given distribution
	// (GET /architectures/{distribution})
	GetArchitectures(ctx echo.Context, distribution string) error
	// compose image
	// (POST /compose)
	ComposeImage(ctx echo.Context) error
	// get a collection of previous compose requests for the logged in user
	// (GET /composes)
	GetComposes(ctx echo.Context, params GetComposesParams) error
	// get status of an image compose
	// (GET /composes/{composeId})
	GetComposeStatus(ctx echo.Context, composeId string) error
	// get metadata of an image compose
	// (GET /composes/{composeId}/metadata)
	GetComposeMetadata(ctx echo.Context, composeId string) error
	// get the available distributions
	// (GET /distributions)
	GetDistributions(ctx echo.Context) error
	// get the openapi json specification
	// (GET /openapi.json)
	GetOpenapiJson(ctx echo.Context) error

	// (GET /packages)
	GetPackages(ctx echo.Context, params GetPackagesParams) error
	// return the readiness
	// (GET /ready)
	GetReadiness(ctx echo.Context) error
	// get the service version
	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetArchitectures converts echo context to params.
func (w *ServerInterfaceWrapper) GetArchitectures(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "distribution" -------------
	var distribution string

	err = runtime.BindStyledParameterWithLocation("simple", false, "distribution", runtime.ParamLocationPath, ctx.Param("distribution"), &distribution)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter distribution: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetArchitectures(ctx, distribution)
	return err
}

// ComposeImage converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeImage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeImage(ctx)
	return err
}

// GetComposes converts echo context to params.
func (w *ServerInterfaceWrapper) GetComposes(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetComposesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetComposes(ctx, params)
	return err
}

// GetComposeStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetComposeStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "composeId" -------------
	var composeId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "composeId", runtime.ParamLocationPath, ctx.Param("composeId"), &composeId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter composeId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetComposeStatus(ctx, composeId)
	return err
}

// GetComposeMetadata converts echo context to params.
func (w *ServerInterfaceWrapper) GetComposeMetadata(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "composeId" -------------
	var composeId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "composeId", runtime.ParamLocationPath, ctx.Param("composeId"), &composeId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter composeId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetComposeMetadata(ctx, composeId)
	return err
}

// GetDistributions converts echo context to params.
func (w *ServerInterfaceWrapper) GetDistributions(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetDistributions(ctx)
	return err
}

// GetOpenapiJson converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenapiJson(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetOpenapiJson(ctx)
	return err
}

// GetPackages converts echo context to params.
func (w *ServerInterfaceWrapper) GetPackages(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPackagesParams
	// ------------- Required query parameter "distribution" -------------

	err = runtime.BindQueryParameter("form", true, true, "distribution", ctx.QueryParams(), &params.Distribution)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter distribution: %s", err))
	}

	// ------------- Required query parameter "architecture" -------------

	err = runtime.BindQueryParameter("form", true, true, "architecture", ctx.QueryParams(), &params.Architecture)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter architecture: %s", err))
	}

	// ------------- Required query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, true, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPackages(ctx, params)
	return err
}

// GetReadiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetReadiness(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/architectures/:distribution", wrapper.GetArchitectures)
	router.POST(baseURL+"/compose", wrapper.ComposeImage)
	router.GET(baseURL+"/composes", wrapper.GetComposes)
	router.GET(baseURL+"/composes/:composeId", wrapper.GetComposeStatus)
	router.GET(baseURL+"/composes/:composeId/metadata", wrapper.GetComposeMetadata)
	router.GET(baseURL+"/distributions", wrapper.GetDistributions)
	router.GET(baseURL+"/openapi.json", wrapper.GetOpenapiJson)
	router.GET(baseURL+"/packages", wrapper.GetPackages)
	router.GET(baseURL+"/ready", wrapper.GetReadiness)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xbe4/bOJL/KoTugEwAyZYf/TIQzPZkM0kfskmQzuT+SBoNWipb3EikQlLd7QT+7gc+",
	"JFEWZbtnk7ub/SejNsmqXz1YrCpyvgcJK0pGgUoRLL4HIsmgwPrz8r+vr2d/lDnD6Xv4WoGQb0tJGNWD",
	"clNCsAjY8p+QyGAburOvJZaVnlVyVgKXBPRfFc+dpUJyQtfBdhsGHL5WhEMaLD7pSTehl/4Qli4XkWEO",
	"t/dEZrc4SVhlBYMHXJQ5KBaT6Wx+cnp2fhFPpooXkVAID7IGBeYcb4IwqCj5WsGVmS55Bbvgfbz3CjOk",
	"KlyQDmj1QxQn57P47GJ2dnZycnGSzpdB2IfMYU0Y7S6GKroHIaNJf8GOAIpvQ8OLnCcZkZDIimtFeKDz",
	"JOuyfzg/vT2d+8CSAq/hVv2slzaGaNd+Tdj91Le0Y5qeGApDl/whYboA/pPDKlgE/zFud8fYbo1xTwU9",
	"NGFw+a3icJy/chCs4gncrjmrSvVLCiLhRM8PFsEbXABiKyQzQPVcpOei+ww46AEtKRIZq/IULQFVmjWk",
	"o880CB11fmBVgul7S+al5uhRrqiWDYRbkvZBXf1dQXKn/QkwczhJz5fTJMLL6Tyazyez6CJOTqLTyXQW",
	"n8J5fAF+0wPFVO7BpUCYScegQh8yIlBO6BcED2WOCRUoY/efqWRoRWiKiESEahrarOgd4xLni880k7IU",
	"i/E4ZYkYFSThTLCVHCWsGAONKjHGav4YJ5LcQZQSDolkfDNeVTTFBVCJc9EbjTJ2H0kWKdaRkWJHbyfJ",
	"GaxOlqfRJJmtonmK4wifTqdRvIxP4+nsIj1Lzw7u9FaJfXOHu07p3Tytiw9FMbP/KC6gu6mLTaSHDoJ0",
	"CPggPFebU8A/QOIUS9wHwITkALcJKwoivd7yS4ZF9rR2mmVFconsdI/nlTj5gteGdpfUOzOCciKUtyR5",
	"lRK6Rm9efHx/GYTHBRZLoxHHF+WGdGCjTF8FSSUkK8g33ISffRCed2dvwyAlSvxlJe2psm/13525oo3v",
	"fQf4x+ZKjajQFoRBgR9eA13LLFhM4njwmOBGRI/yL5V6lA3hAScy3yBG6/1uF43QK3ynDFIwvjMk1OZW",
	"CxKjSUQESirOgSpKlEkkqrJkXNYB7Chbavlqo2y1jDZvmIRBQWj7x2NzjI5Berq52eciomRUgGefpofz",
	"MpIGNy2t/TteNKMHVWQJ+Te+pdPj+4JzxvvMU5CY5OpT+YwrE6ES1sBNfoSF8eSD8jaTHQBiWIt1CDrK",
	"P3bJDSUS6ljy6HlFuNns7Z4a45KMtd4iFcZS4OO7ydg6tfg1JwWRzybx5yqOp6dstRIgn8W+IJfjH0F6",
	"Eh+M7kYIy9DnuAX4grrOq33G3SFv5vXp7kzTTGpFh8aKPoP7s92EA5aQ3mLpLSC8O2s3Lnpy+DqYD3il",
	"GQ5d7hpyL9bvek0OYiOsIEf56e/tEo93uuehU2CVTMg1B/E1f0R5pcltVDpxy6FkgkjGySPS8vf1oo2P",
	"tJviHKJ07c7dhkElgHtOHX3UsxXSw0hmWCKMzHELHCWYIpymIcK5YEiUkJDVRp1AMgPCVSZfgs78TC4v",
	"EKYpur5+hb7ARhx7yvwhTFA7nCa4R7PfkzvCubv/PaToFZboBZXAS04EoNeEVg/ol/evXrx+is5H3tqu",
	"f+rzDPLofH4wLlCTFriAbg6IZDyQVoVab/iojdIwNF8nzddp/XXRfKh4lQCVTOi19vPCYd3K1mHtnghH",
	"Wa1nC4+//t7Zql1LFYTeCvKtq91JPJ2HwUO0ZpGlVREqT+c6jqpIWDJCd+P6HeYHreEsDlvWPoO8fP7u",
	"X2rRdLfXa7u97nBOUvSSsXUOqJ6OJEOaii3tTH6GVMyuJKA3LK2zPMVl9Jm+wEmGjISoqIRK8qnEhCJs",
	"9yYBXlcBlglSAo7QR81/xXiBpUCYw+IzRShCT9S+X3yHApOcpNsnC3RJkf5L7XsOwsYEDiUHoRyg5ZUo",
	"EmhHqBH6nXFkrROiJzgnCfzN/q2Kyicjy1kAvyMJXJp1j8RgWFsSQ7yLTcRkBjzCZfk3XJaiZHK0tovq",
	"NS4kHcQeqw0rv147Mrh2VJAWhAqvDlJWYEIX381/FcMPGaCX6LoiEpD5Ff1SclJgvnnaZ57nhqEyuIng",
	"2vpY2rW7GllrrBoCYhw96WFC6GplygXrT2l40DmJMCuUJ6faVRGmG0Ot1nK3+P+kT6NFzzdUFd/1imNN",
	"GISBMV5f2SoIGzW7P/6fdEyb2PLjeg2hoqDo206S02wVCdAUUxktOSZpNItnJ5PZwUjpkAsPtS5effjw",
	"bm8Z49cukTkcrl3MtLCmdOPyU2G1zxPU0PG5Vov+UCfWElYQOiWxt21cd1X7h8Hzd38gd0YdqrWWQ8Ro",
	"vkGmzdwt33dK9zpDsB3pm70t6aPq1w+6ubwNbavp0Jq31x/ULJVUljbVbfSxN9Fzz1Vvu7vRXUeERu9D",
	"2wZqHzyiWHWLb5VSNyRrtYoqSUCo7HWFSW7AlEBTpdow0KWj+TTCm28OayIkaP3fuG3OllrPSFZ5x/UZ",
	"OnGjF3/aFoNjT0cmfK8Q6EaucqB0DVHTH9R/ESokznNQmdQ6KdW/ykhN1DF1szvrTpQZaHL2ukXln13K",
	"7U+dhVnq9VnrVT3jllhtA89uwhQtAQFR54MqWjRb9IvV/QLF09N4vpym+BQuTubLdDZfni/Pp/h8dgIn",
	"+OwsnS5P49UKPw3VWYjRkmOaZFFOvgDisAIONAGHnhJnfD42226s5Hq609Puz/Bfbq36JcXhZYMXj72w",
	"bFuwfVUO1uqiKlSGcTgo26qmnn/TchvuX9d3aT2uULKBkT1NhRywGBCCrIv0ZGiI4jooDxz3noE74IIc",
	"02fTo2GtnXpZCzesL/MsRkdvP6oXVxv9J7Tf6gbJQPvN/OV2dEej0ehfacrtZzg5muNfp1XnAfMe1OGi",
	"zg7PbasztF/mdqqfR9Nu6jFZYgE25rT2qi8Lk5SOOKQZNheFqg4FKsfKJGMVzs7beKboMDFmYqyOVF2B",
	"qrqeE5+HJBkkX27X5dqRbMlYDlg3sdbl+gts/N3INWUcboXI/UuV2pXO/fIURKd4oxWkjGObA48YX4/r",
	"db9yKNkzMx7NpsYF1a5+1rwMOCScYZKT3U2gQDQY1PDI9G00/19tDHl2HqnkDBcOZ6z+PZ2bXzS+37CA",
	"t9dHYOGZKHyK2nUfNc3nOdc7rcidkJ9IcqcbuJG1V6eWEZBwkHrIQVpiIe4ZT31wlRNFXm/sO6P3jQYV",
	"ZJ3tPKJRpVzocRXG15jaBnRnwTSex7PpPPTcyKiSFHgfotuyHSltOkgPBqwOkHBXqx2mjoocaX2W62bh",
	"/dvmtt+F6ebtKlh8OvCSZOBN0zY8uG7gZdahlUMtuoMcB9+zbG+cNOBwGm7rJX8SUCtwWPdDZYyjekbh",
	"Maqv64LjVX7kit2OxSNUXK+4+RNVFq8otaXUYLb2Z81ksYQ9ezX2GSifTF1UF1H4XozEzItQX2gMJt9t",
	"bKgE8In35ZLIbntxU4gs4gKjy8vLy99mb77h55NjLyFqej6X/NjmuF28Rye/9cSb7VZH2hXrF2vXtlNr",
	"O5g53gjbPdRpX/OMQSdGCdh02KgsuCxxkgGajuLAlkHNuX1/fz/CelgflnatGL++ev7izfWLaDqKR5ks",
	"cqfvZErkOt2se8hO2r4IJqNYnwMlUFySYBHMRvFIabvEMtPKGbvdCjH+7uaiWzVhDdJsaeA6Yl+lwSJ4",
	"CbL7Wk9R5LgAqe/mPu1qzaWKVoyj+4wkGZIM5Yx9QVWJ8B0mOV7m0GksiV5Vai6QCNXHrMzqWmWx+xCj",
	"tas5HM2G8vnAjX5fpSsXrZFpHJtkWWeC+vgoy5wkWvrxP+1zhZbesY8T1QbehjuKwai+txxQgL6INJeU",
	"WAiWECwhtR4nm7DQlL3KXObWZICIs9JhudJ9gzW5A4o6ilTE66cFemcx4elgNG91bJOl6yy2X3VlB+0O",
	"+Y2lmx+m551nVx5F29coStNWBQwtm1dGac9jtj2vmPx4tLZe9sCtNZphgYTEXEKqNvL8B/pmtwftwaDc",
	"qMZhjYaIQAXOVaarAHU8r+sEruOIfXGkfthxKIQU+AFhffupbFhTDlEKK1zlEk3iuA4MXyvgmzYy6No7",
	"cEOAXWMfuBWEkkKdj5PQUxkP+LpApfIiU8m3KIYwmHl+EC6E2APhZwao3juqvTGqsWc/5mCUsDyHREd4",
	"tkIlhzvCKrHrQULHGuVaOVuvVSij+sKv6zDj7/brKnUPoS4uk//o2Entpq4jVTjoZ9d10rTX2a5SR1xk",
	"GUmG1tqGntOngfv/5ujpyrsnxIi2Fd816R79DhpLdxnqdp/XavUEc+Ycb7imLfso0zXc/pLGa98eD5uv",
	"aOfsGrARftCE6e6jnaEo3X3d8xMl97/lOTJz6oozkBjtmT22ifKoxjykjrdm3n8Jm2v2ldEFy0FWnAok",
	"MyJQypKqUIryA7QYkMLQvFCpOycSr0XTe73RmN1Xf0N46xb9o/J0JzuveahNO3DCHZ1/P+LJev/07dw6",
	"Pw7gzrXsMMCD19J9WA37GtIwDAH2BuX4SBPuz4Vq5v/7uVAj9r9FLtS7x9obdZptt9XTxhywKWiG9mB7",
	"DfITZWiZeMBzZ9CNPCY62f+lzZ0ydlon3sO8jln1+7X2wrAn/kfnLvEnCV+z8NptF6I/+PZnNS1xEy9N",
	"18Z726d7invGR3Gwvdn+TwAAAP//1jLcHOM7AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
