apiVersion: v1
kind: Template
labels:
  app: image-builder
  template: image-builder
metadata:
  annotations:
    description: Backend service for image-builder in cloud.redhat.com
  name: image-builder
objects:

# NOTE(mhayden): This came from the example in the documentation and I felt
# like it would be useful to maintain it here so it's easier to add our own
# variables later.
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: image-builder
    name: image-builder-config
  data:
    example: "${EXAMPLE}"

# Deploy the image-builder container.
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: image-builder
    name: image-builder
  spec:
    replicas: 2
    selector:
      matchLabels:
        name: image-builder
    template:
      metadata:
        labels:
          name: image-builder
      spec:
        containers:
        - image: "${IMAGE_NAME}:${IMAGE_TAG}"
          name: image-builder
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: ${HEALTHCHECK_URI}
              port: 8086
              scheme: HTTP
              httpHeaders:
                - name: X-Rh-Identity
                  value: health-check
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: ${HEALTHCHECK_URI}
              port: 8086
              scheme: HTTP
              httpHeaders:
                - name: X-Rh-Identity
                  value: health-check
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - name: api
            containerPort: 8086
            protocol: TCP
          volumeMounts:
            - name: composer-secrets
              mountPath: "/app/composer-secrets"
              readOnly: true
          env:
            - name: LISTEN_ADDRESS
              value: "${LISTEN_ADDRESS}"
            # Credentials/configuration for AWS RDS.
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.port
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.name
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.password
            # Credentials/configuration for AWS cloudwatch.
            - name: CW_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: image-builder-cloudwatch
            - name: CW_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: image-builder-cloudwatch
            - name: CW_LOG_GROUP
              valueFrom:
                secretKeyRef:
                  key: log_group_name
                  name: image-builder-cloudwatch
            - name: CW_AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: aws_region
                  name: image-builder-cloudwatch
            - name: OSBUILD_AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: aws_region
                  name: composer-secrets
            - name: OSBUILD_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: composer-secrets
            - name: OSBUILD_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: composer-secrets
            - name: OSBUILD_AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  key: aws_s3_bucket
                  name: composer-secrets
            - name: OSBUILD_URL
              value: "${OSBUILD_URL}"
            - name: OSBUILD_CERT_PATH
              value: "${OSBUILD_CERT_PATH}"
            - name: OSBUILD_KEY_PATH
              value: "${OSBUILD_KEY_PATH}"
            - name: OSBUILD_CA_PATH
              value: "${OSBUILD_CA_PATH}"

# Deploy the osbuild-composer container.
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: osbuild-composer
    name: osbuild-composer
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: osbuild-composer
    template:
      metadata:
        labels:
          name: osbuild-composer
      spec:
        containers:
        - image: "${COMPOSER_IMAGE}:${COMPOSER_TAG}"
          name: osbuild-composer
          ports:
          - name: api
            containerPort: 443
            protocol: TCP
          volumeMounts:
            - name: composer-secrets
              mountPath: "/etc/osbuild-composer"
              readOnly: true
            - name: osbuild-state-dir
              mountPath: "/var/lib/osbuild-composer"
            - name: osbuild-cache-dir
              mountPath: "/var/cache/osbuild-composer"
        volumes:
        - name: composer-secrets
          secret:
            secretName: composer-secrets
        - emptyDir: {}
          name: osbuild-state-dir
        - emptyDir: {}
          name: osbuild-cache-dir

# Set up a service within the namespace for the backend.
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: image-builder
    name: image-builder
  spec:
    ports:
      - name: image-builder
        protocol: TCP
        port: ${{BACKEND_LISTENER_PORT}}
        targetPort: 8086
    selector:
      name: image-builder

# Service for composer
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: osbuild-composer
    name: osbuild-composer
  spec:
    ports:
      - name: osbuild-composer-cloudapi
        protocol: TCP
        port: ${{BACKEND_LISTENER_PORT}}
        targetPort: 443
      - name: osbuild-composer-remote-worker
        protocol: TCP
        port: ${{COMPOSER_REMOTE_WORKER_PORT}}
        targetPort: 8700
    selector:
      name: image-builder

# Parameters for the various configurations shown above.
parameters:
  - description: Example configmap variable
    name: EXAMPLE
    value: "EXAMPLE_DATA"
  - description: image-builder image name
    name: IMAGE_NAME
    value: quay.io/cloudservices/image-builder
    required: true
  - description: image-builder image tag
    name: IMAGE_TAG
    required: true
  # NOTE(mhayden): This is set to match the ports set up in RHIOPS-953.
  - description: Backend listener port
    name: BACKEND_LISTENER_PORT
    value: "8080"
  - description: Composer remote worker port
    name: COMPOSER_REMOTE_WORKER_PORT
    value: "8700"
  # NOTE(mhayden): Change this later once we add a real health check to
  # image-builder that verifies connectivity, etc.
  - name: HEALTHCHECK_URI
    description: URI to query for the health check
    value: "/api/image-builder/v1/version"
  - name: LISTEN_ADDRESS
    description: Listening address and port
    value: "0.0.0.0:8086"
  - name: OSBUILD_CERT_PATH
    description: Path to certificate for ssl client auth to osbuild-composer instance
    value: "/app/composer-secrets/client-crt.pem"
  - name: OSBUILD_KEY_PATH
    description: Path to key for ssl client auth to osbuild-composer instance
    value: "/app/composer-secrets/client-key.pem"
  - name: OSBUILD_CA_PATH
    description: Path to ca for ssl client auth to osbuild-composer instance
    value: "/app/composer-secrets/ca-crt.pem"
  - name: OSBUILD_URL
    description: Url to osbuild-composer instance
    value: "https://osbuild-composer.image-builder-stage.svc.cluster.local:8080"
  - name: COMPOSER_IMAGE
    value: "quay.io/cloudservices/osbuild-composer"
    description: osbuild-composer image name
  - name: COMPOSER_TAG
    value: "946a0b4"
    description: osbuild-composer version
