apiVersion: v1
kind: Template
labels:
  app: image-builder
  template: image-builder
metadata:
  annotations:
    description: Backend service for image-builder in console.redhat.com
  name: image-builder
objects:

# Deploy the image-builder container.
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: image-builder
    name: image-builder
  spec:
    replicas: 3
    selector:
      matchLabels:
        name: image-builder
    strategy:
      # Update pods 1 at a time
      type: RollingUpdate
      rollingUpdate:
        # Create at most 1 extra pod over .spec.replicas
        maxSurge: 1
        # At all times there should be .spec.replicas available
        maxUnavailable: 0
    template:
      metadata:
        labels:
          name: image-builder
      spec:
        containers:
        - image: "${IMAGE_NAME}:${IMAGE_TAG}"
          name: image-builder
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: ${LIVENESS_URI}
              port: 8086
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: ${READINESS_URI}
              port: 8086
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10 # The readiness probe is pinging osbuild-composer
          ports:
          - name: api
            containerPort: 8086
            protocol: TCP
          volumeMounts:
            - name: composer-secrets
              mountPath: "/app/composer-secrets"
              readOnly: true
            - name: config-volume
              mountPath: /app/quotas
          env:
            - name: LISTEN_ADDRESS
              value: "${LISTEN_ADDRESS}"
            # Credentials/configuration for AWS RDS.
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.port
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.name
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.password
            - name: PGSSLMODE
              value: "${PGSSLMODE}"
            # Configuration for the osbuild client within image-builder
            - name: OSBUILD_URL
              value: "${OSBUILD_URL}"
            - name: OSBUILD_CERT_PATH
              value: "${OSBUILD_CERT_PATH}"
            - name: OSBUILD_KEY_PATH
              value: "${OSBUILD_KEY_PATH}"
            - name: OSBUILD_CA_PATH
              value: "${OSBUILD_CA_PATH}"
            # Credentials/configuration for AWS cloudwatch.
            - name: CW_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: image-builder-cloudwatch
            - name: CW_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: image-builder-cloudwatch
            - name: CW_LOG_GROUP
              valueFrom:
                secretKeyRef:
                  key: log_group_name
                  name: image-builder-cloudwatch
            - name: CW_AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: aws_region
                  name: image-builder-cloudwatch
            # Secrets used to tell osbuild-composer where to upload images.
            - name: OSBUILD_AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: aws_region
                  name: composer-secrets
            - name: OSBUILD_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: composer-secrets
            - name: OSBUILD_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: composer-secrets
            - name: OSBUILD_AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  key: aws_s3_bucket
                  name: composer-secrets
            # GCP target specific variables passed to composer
            - name: OSBUILD_GCP_REGION
              value: "${OSBUILD_GCP_REGION}"
            - name: OSBUILD_GCP_BUCKET
              value: "${OSBUILD_GCP_BUCKET}"
            # Azure target specific variables passed to composer
            - name: OSBUILD_AZURE_LOCATION
              value: "${OSBUILD_AZURE_LOCATION}"
            - name: ALLOWED_ORG_IDS
              value: "${ALLOWED_ORG_IDS}"
            - name: ALLOWED_ACCOUNT_NUMBERS
              value: "${ALLOWED_ACCOUNT_NUMBERS}"
            - name: DISTRIBUTIONS_DIR
              value: "${DISTRIBUTIONS_DIR}"
            - name: QUOTA_FILE
              value: "/app/quotas/accounts_quotas.json"
        volumes:
          - name: composer-secrets
            secret:
              secretName: composer-secrets
          - name: config-volume
            configMap:
              name: image-builder-crc-quotas
              items:
              - key: quotas.json
                path: accounts_quotas.json
        initContainers:
        - name: image-builder-migrate
          image: "${IMAGE_NAME}:${IMAGE_TAG}"
          command: [ "/app/image-builder-migrate-db" ]
          env:
          - name: MIGRATIONS_DIR
            value: "${MIGRATIONS_DIR}"
          # Credentials/configuration for AWS RDS.
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: image-builder-db
                key: db.host
          - name: PGPORT
            valueFrom:
              secretKeyRef:
                name: image-builder-db
                key: db.port
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: image-builder-db
                key: db.name
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: image-builder-db
                key: db.user
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: image-builder-db
                key: db.password
          - name: PGSSLMODE
            value: "${PGSSLMODE}"
          # Credentials/configuration for AWS cloudwatch.
          - name: CW_AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws_access_key_id
                name: image-builder-cloudwatch
          - name: CW_AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws_secret_access_key
                name: image-builder-cloudwatch
          - name: CW_LOG_GROUP
            valueFrom:
              secretKeyRef:
                key: log_group_name
                name: image-builder-cloudwatch
          - name: CW_AWS_REGION
            valueFrom:
              secretKeyRef:
                key: aws_region
                name: image-builder-cloudwatch

# Set up a service within the namespace for the backend.
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: image-builder
    name: image-builder
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/scrape: 'true'
  spec:
    ports:
      - name: image-builder
        protocol: TCP
        port: ${{BACKEND_LISTENER_PORT}}
        targetPort: 8086
    selector:
      name: image-builder

# Parameters for the various configurations shown above.
parameters:
  - description: image-builder image name
    name: IMAGE_NAME
    value: quay.io/cloudservices/image-builder
    required: true
  - description: image-builder image tag
    name: IMAGE_TAG
    required: true
  - description: osbuild-composer image name
    name: OSBUILD_IMAGE_NAME
    value: quay.io/cloudservices/osbuild-composer
    required: true
  - description: osbuild-composer image tag
    name: OSBUILD_IMAGE_TAG
    value: INSERTHASH # Pin the osbuild-composer version, we should always a working and tested version here
    required: true
  # NOTE(mhayden): This is set to match the ports set up in RHIOPS-953.
  - description: Backend listener port
    name: BACKEND_LISTENER_PORT
    value: "8080"
  - name: LIVENESS_URI
    description: URI to query for the liveness check
    value: "/status"
  - name: READINESS_URI
    description: URI to query for the readiness check
    value: "/ready"
  - name: LISTEN_ADDRESS
    description: Listening address and port
    value: "0.0.0.0:8086"
  - name: OSBUILD_CERT_PATH
    description: Path to certificate for ssl client auth to osbuild-composer instance
    value: "/app/composer-secrets/client-crt.pem"
  - name: OSBUILD_KEY_PATH
    description: Path to key for ssl client auth to osbuild-composer instance
    value: "/app/composer-secrets/client-key.pem"
  - name: OSBUILD_CA_PATH
    description: Path to ca for ssl client auth to osbuild-composer instance
    value: "/app/composer-secrets/ca-crt.pem"
  - name: OSBUILD_URL
    description: Url to osbuild-composer instance in AWS
    value: ""
  - name: ALLOWED_ORG_IDS
    description: Organization ids allowed to access the api, wildcard means everyone
    value: ""
  - name: ALLOWED_ACCOUNT_NUMBERS
    description: Account numbers allowed to access the api, wildcard means everyone
    value: ""
  - name: DISTRIBUTIONS_DIR
    description: Directory which contains json files detailing available distributions, their repositories, and their packages
    value: "/app/distributions"
  - name: OSBUILD_GCP_REGION
    description: Region in GCP to upload to
    value: "us-east4"
  - name: OSBUILD_GCP_BUCKET
    description: Bucket in GCP to upload to
    value: "image-upload-bkt-us"
  - name: OSBUILD_AZURE_LOCATION
    description: Location in Azure to upload to
    value: "eastus"
  - name: MIGRATIONS_DIR
    description: Directory containing migration files for aws rds
    value: "/app/migrations"
  - name: PGSSLMODE
    description: Sslmode for the connection to psql
    value: "require"
