apiVersion: v1
kind: Template
labels:
  app: image-builder
  template: image-builder
metadata:
  annotations:
    description: Backend service for image-builder in cloud.redhat.com
  name: image-builder
objects:

# NOTE(mhayden): This came from the example in the documentation and I felt
# like it would be useful to maintain it here so it's easier to add our own
# variables later.
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: image-builder
    name: image-builder-config
  data:
    example: "${EXAMPLE}"

# Deploy the image-builder container, add an environment variable from the
# configmap, and open a port.
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: image-builder
    name: image-builder
  spec:
    replicas: 2
    selector:
      matchLabels:
        name: image-builder
    template:
      metadata:
        labels:
          name: image-builder
      spec:
        containers:
        - image: "${IMAGE_NAME}:${IMAGE_TAG}"
          name: image-builder
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: ${HEALTHCHECK_URI}
              port: 8086
              scheme: HTTP
              httpHeaders:
                - name: X-Rh-Identity
                  value: health-check
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: ${HEALTHCHECK_URI}
              port: 8086
              scheme: HTTP
              httpHeaders:
                - name: X-Rh-Identity
                  value: health-check
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - name: api
            containerPort: 8086
            protocol: TCP
          env:
            - name: LISTEN_ADDRESS
              value: "${LISTEN_ADDRESS}"
            # Credentials/configuration for AWS RDS.
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.port
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.name
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: image-builder-db
                  key: db.password
            # Credentials/configuration for AWS cloudwatch.
            - name: CW_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: image-builder-cloudwatch
            - name: CW_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: image-builder-cloudwatch
            - name: CW_LOG_GROUP_NAME
              valueFrom:
                secretKeyRef:
                  key: log_group_name
                  name: image-builder-cloudwatch
            - name: CW_AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: aws_region
                  name: image-builder-cloudwatch

# Set up a service within the namespace for the backend.
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: image-builder
    name: image-builder
  spec:
    ports:
      - name: image-builder
        protocol: TCP
        port: ${{BACKEND_LISTENER_PORT}}
        targetPort: 8086
    selector:
      name: image-builder

# Parameters for the various configurations shown above.
parameters:
  - description: Example configmap variable
    name: EXAMPLE
    value: "EXAMPLE_DATA"
  - description: image-builder image name
    name: IMAGE_NAME
    value: quay.io/cloudservices/image-builder
    required: true
  - description: image-builder image tag
    name: IMAGE_TAG
    required: true
  # NOTE(mhayden): This is set to match the ports set up in RHIOPS-953.
  - description: Backend listener port
    name: BACKEND_LISTENER_PORT
    value: "8080"
  # NOTE(mhayden): Change this later once we add a real health check to
  # image-builder that verifies connectivity, etc.
  - name: HEALTHCHECK_URI
    description: URI to query for the health check
    value: "/api/image-builder/v1/version"
  - name: LISTEN_ADDRESS
    description: Listening address and port
    value: "0.0.0.0:8086"
