---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: image-builder
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: image-builder
  spec:
    envName: ${ENV_NAME}
    testing:
      iqePlugin: image-builder
    deployments:
    - name: service
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: ${LIVENESS_URI}
            port: 8000
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: ${READINESS_URI}
            port: 8000
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        env:
          - name: LISTEN_ADDRESS
            value: ${LISTEN_ADDRESS}
          - name: COMPOSER_TOKEN_URL
            value: "${COMPOSER_TOKEN_URL}"
          - name: DISTRIBUTIONS_DIR
            value: '/app/distributions'
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: COMPOSER_URL
            value: "${COMPOSER_URL}"
          - name: COMPOSER_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: client_id
                name: composer-secrets
          - name: COMPOSER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: client_secret
                name: composer-secrets
        initContainers:
        - name: image-builder-migrate
          image: ${IMAGE}:${IMAGE_TAG}
          command: [ "/app/image-builder-migrate-db" ]
          env:
          - name: MIGRATIONS_DIR
            value: "${MIGRATIONS_DIR}"

      # Enable access to the api
      webServices:
        public:
          enabled: true
          apiPath: image-builder/v1
        private:
          enabled: false
        metrics:
          enabled: false

      # add database
    database:
      name: image-builder
      version: 12

# service to access image-builder also on 8080
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: image-builder
    name: image-builder
  spec:
    ports:
      - name: image-builder-8080
        protocol: TCP
        port: 8080
        targetPort: 8000
    selector:
      pod: image-builder-service

parameters:
  - name: IMAGE
    value: quay.io/cloudservices/image-builder
    required: true
  - name: IMAGE_TAG
    required: true
  - name: LIVENESS_URI
    value: "/status"
  - name: READINESS_URI
    value: "/ready"
  - name: LISTEN_ADDRESS
    value: "0.0.0.0:8000"
  - description: Determines Clowder deployment
    name: CLOWDER_ENABLED
    value: "true"
  - description: ClowdEnv Name
    name: ENV_NAME
  - name: COMPOSER_URL
    value: "https://api.stage.openshift.com"
  - name: COMPOSER_TOKEN_URL
    value: "https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token"
  - name: MIGRATIONS_DIR
    description: Directory containing migration files for aws rds
    value: "/app/migrations"
