apiVersion: v1
kind: Template
metadata:
  name: image-builder-iqe-trigger
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: image-builder-iqe-trigger
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        containers:
          - image: "quay.io/app-sre/ubi8-ubi-minimal:8.6"
            name: image-builder-iqe-trigger
            command: ["curl"]
            args: ["-X", "POST", "-H", 'Content-type: application/json', "--data", '{"text":"Trigger IQE pipeline."}', "${WEBHOOK_URL}"]

parameters:
  - name: WEBHOOK_URL
    value: ''
    required: true
