---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: image-builder-tests
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: image-builder-${TEST_TYPE}-tests-${IMAGE_TAG}-${UID}
    annotations:
      "ignore-check.kube-linter.io/no-liveness-probe": "probes not required on Job pods"
      "ignore-check.kube-linter.io/no-readiness-probe": "probes not required on Job pods"
  spec:
    backoffLimit: 0
    template:
      spec:
        serviceAccountName: ${SERVICE_ACCOUNT}
        restartPolicy: Never
        volumes:
        - name: sel-shm
          emptyDir:
            medium: Memory
        - name: sel-downloads
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
        containers:
        - name: image-builder-iqe-${TEST_TYPE}-tests-${IMAGE_TAG}-${UID}
          image: ${IQE_IMAGE}
          imagePullPolicy: Always
          args:
          - run
          env:
          - name: ENV_FOR_DYNACONF
            value: ${ENV_FOR_DYNACONF}
          - name: DYNACONF_MAIN__use_beta
            value: ${USE_BETA}
          - name: IQE_IBUTSU_SOURCE
            value: image-builder-${IMAGE_TAG}-tests-${UID}-${ENV_FOR_DYNACONF}
          - name: IQE_BROWSERLOG
            value: ${IQE_BROWSERLOG}
          - name: IQE_NETLOG
            value: ${IQE_NETLOG}
          - name: IQE_PLUGINS
            value: ${IQE_PLUGINS}
          - name: IQE_MARKER_EXPRESSION
            value: ${IQE_MARKER_EXPRESSION}
          - name: IQE_FILTER_EXPRESSION
            value: ${IQE_FILTER_EXPRESSION}
          - name: IQE_LOG_LEVEL
            value: ${IQE_LOG_LEVEL}
          - name: IQE_REQUIREMENTS
            value: ${IQE_REQUIREMENTS}
          - name: IQE_PARALLEL_ENABLED
            value: ${IQE_PARALLEL_ENABLED}
          - name: IQE_REQUIREMENTS_PRIORITY
            value: ${IQE_REQUIREMENTS_PRIORITY}
          - name: IQE_TEST_IMPORTANCE
            value: ${IQE_TEST_IMPORTANCE}
          - name: DYNACONF_IQE_VAULT_LOADER_ENABLED
            value: "true"
          - name: DYNACONF_IQE_VAULT_VERIFY
            value: "true"
          - name: DYNACONF_IQE_VAULT_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: iqe-vault
                optional: true
          - name: DYNACONF_IQE_VAULT_MOUNT_POINT
            valueFrom:
              secretKeyRef:
                key: mountPoint
                name: iqe-vault
                optional: true
          - name: DYNACONF_IQE_VAULT_ROLE_ID
            valueFrom:
              secretKeyRef:
                key: roleId
                name: iqe-vault
                optional: true
          - name: DYNACONF_IQE_VAULT_SECRET_ID
            valueFrom:
              secretKeyRef:
                key: secretId
                name: iqe-vault
                optional: true
          resources:
            limits:
              cpu: ${IQE_CPU_LIMIT}
              memory: ${IQE_MEMORY_LIMIT}
            requests:
              cpu: ${IQE_CPU_REQUEST}
              memory: ${IQE_MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: sel-downloads
              mountPath: /sel-downloads
        - name: image-builder-sel-${TEST_TYPE}-tests-${IMAGE_TAG}-${UID}
          image: ${IQE_SEL_IMAGE}
          env:
            - name: _JAVA_OPTIONS
              value: ${SELENIUM_JAVA_OPTS}
            - name: VNC_GEOMETRY
              value: ${VNC_GEOMETRY}
          resources:
            limits:
              cpu: ${SELENIUM_CPU_LIMIT}
              memory: ${SELENIUM_MEMORY_LIMIT}
            requests:
              cpu: ${SELENIUM_CPU_REQUEST}
              memory: ${SELENIUM_MEMORY_REQUEST}
          volumeMounts:
            - name: sel-shm
              mountPath: /dev/shm
            - name: sel-downloads
              mountPath: /home/selenium/Downloads

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${SERVICE_ACCOUNT}
  imagePullSecrets:
  - name: quay-cloudservices-pull

parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: UID
  description: "Unique job name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
- name: IQE_IMAGE
  description: "container image path for the iqe plugin"
  value: quay.io/cloudservices/iqe-tests:insights-experiences
- name: ENV_FOR_DYNACONF
  value: stage_proxy
- name: USE_BETA
  value: "true"
- name: IQE_PLUGINS
  value: insights_experiences
- name: IQE_MARKER_EXPRESSION
  value: 'image_builder'
- name: IQE_FILTER_EXPRESSION
  value: ''
- name: IQE_LOG_LEVEL
  value: info
- name: IQE_REQUIREMENTS
  value: ''
- name: IQE_REQUIREMENTS_PRIORITY
  value: ''
- name: IQE_TEST_IMPORTANCE
  value: ''
- name: IQE_SEL_IMAGE
  value: 'quay.io/redhatqe/selenium-standalone:ff_91.9.1esr_chrome_103.0.5060.114'
- name: IQE_BROWSERLOG
  value: "1"
- name: IQE_NETLOG
  value: "1"
- name: TEST_TYPE
  value: ''
- name: IQE_CPU_LIMIT
  value: "1"
- name: IQE_MEMORY_LIMIT
  value: 1.5Gi
- name: IQE_CPU_REQUEST
  value: 250m
- name: IQE_MEMORY_REQUEST
  value: 1Gi
- name: SELENIUM_CPU_LIMIT
  value: 500m
- name: SELENIUM_MEMORY_LIMIT
  value: 2Gi
- name: SELENIUM_CPU_REQUEST
  value: 100m
- name: SELENIUM_MEMORY_REQUEST
  value: 1Gi
- name: SELENIUM_JAVA_OPTS
  value: ''
- name: VNC_GEOMETRY
  value: '1920x1080'
- name: SERVICE_ACCOUNT
  value: 'iqe-image-builder'
- name: IQE_PARALLEL_ENABLED
  value: "false"
