apiVersion: v1
kind: Template
metadata:
  name: image-builder-iqe-trigger
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: image-builder-iqe-trigger
    annotations:
      ignore-check.kube-linter.io/no-liveness-probe
      ignore-check.kube-linter.io/no-readiness-probe
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        serviceAccountName: image-builder
        containers:
          - image: "quay.io/app-sre/ubi8-ubi-minimal:8.6"
            name: image-builder-iqe-trigger
            command: ["curl"]
            args: ["-X", "POST", "-H", 'Content-type: application/json', "--data", '{"text":"Trigger IQE pipeline."}', "${WEBHOOK_URL}"]
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: image-builder

parameters:
  - name: WEBHOOK_URL
    value: ''
    required: true
