#!/usr/bin/env python3
import argparse
import json
import os
import pathlib

import imgtestlib as testlib


# pylint: disable=too-many-branches
def main():
    desc = "Boot an image in the cloud environment it is built for and validate the configuration"
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument("image_search_path", type=str, help="path to search for image file")
    parser.add_argument("config", type=str, help="path to build configuration")
    parser.add_argument(
        "--keep-booted", action="store_true",
        help="keep the image booted (only qcow2 supported right now)")

    args = parser.parse_args()
    search_path = args.image_search_path
    build_config_path = args.config

    image_path = testlib.find_image_file(search_path)
    build_info = testlib.read_build_info(search_path)
    distro = build_info["distro"]
    arch = build_info["arch"]
    image_type = build_info["image-type"]

    # NOTE: Some installer ISOs have embedded kickstart, but they are interactive, so we need to embed
    # a custom kickstart with non-interactive settings in it. To preserve the original kickstart content,
    # we need to read the original kickstart content from the build directory and merge it with the custom
    # kickstart content.
    iso_embedded_ks = build_info.get("iso-embedded-ks", None)
    iso_embedded_ks_path = None
    if iso_embedded_ks:
        iso_embedded_ks_path = os.path.join(search_path, iso_embedded_ks)
        if not os.path.exists(iso_embedded_ks_path):
            raise RuntimeError(f"'iso-embedded-ks' specified in the info.json, but file not found: {iso_embedded_ks_path}")

    config = json.loads(pathlib.Path(build_config_path).read_text(encoding="utf8"))
    if not testlib.can_boot_test(image_type, testlib.read_manifest(search_path),
                                 image_type, arch, distro, config.get("blueprint", {})):
        print(f"SKIP: {image_type} boot tests on {arch} are not supported ({distro})")
        return

    print(f"Testing image at {image_path}")
    bib_image_id = ""
    match image_type:
        # Not all qcow2 types can be boot-tested, for example `server-qcow2` uses
        # initial-setup and this blocks the boot.
        case "qcow2" | "generic-qcow2" | "cloud-qcow2":
            testlib.boot_qemu(arch, image_path, build_config_path, keep_booted=args.keep_booted)
        case "image-installer" | "minimal-installer":
            testlib.boot_qemu_iso(arch, image_path, build_config_path)
        case "network-installer" | "everything-network-installer" | "bootc-generic-iso":
            testlib.boot_qemu_iso_no_unattended_support(arch, image_path, build_config_path)
        case "pxe-tar-xz":
            testlib.boot_qemu_pxe(arch, image_path)
        case "ami" | "ec2" | "ec2-ha" | "ec2-sap" | "edge-ami" | "cloud-ec2":
            testlib.boot_ami(distro, arch, image_type, image_path, build_config_path)
        case "vhd":
            testlib.boot_vhd(distro, arch, image_path, build_config_path)
        case "iot-bootable-container":
            manifest_id = build_info["manifest-checksum"]
            testlib.boot_container(distro, arch, image_type, image_path, manifest_id, build_config_path)
            bib_ref = testlib.get_bib_ref()
            bib_image_id = testlib.skopeo_inspect_id(f"docker://{bib_ref}", testlib.host_container_arch())
        case "wsl" | "generic-wsl":
            if distro == "fedora-41":
                print(f"{distro} {image_type} boot tests are not supported, fails on wsl import")
                return
            testlib.boot_wsl(distro, arch, image_path, build_config_path)
        case _:
            raise testlib.MissingBootImplementation(f"{arch} {image_type} is missing a boot implementation.")

    print("✅ Marking boot successful")
    # amend build info with boot success
    # search_path is the root of the build path (build/build_name)
    build_info["boot-success"] = True
    testlib.write_build_info(search_path, build_info)
    if bib_image_id:
        # write a separate file with the bib image ID as filename to mark the boot success with that image
        bib_id_file = os.path.join(search_path, f"bib-{bib_image_id}")
        print(f"Writing bib image ID file: {bib_id_file}")
        with open(bib_id_file, "w", encoding="utf-8") as fp:
            fp.write("")


if __name__ == "__main__":
    main()
