#!/usr/bin/env python3
import argparse

import imgtestlib as testlib


def main():
    desc = "Boot an image in the cloud environment it is built for and validate the configuration"
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument("image_search_path", type=str, help="path to search for image file")
    parser.add_argument("config", type=str, help="path to build configuration")
    parser.add_argument(
        "--keep-booted", action="store_true",
        help="keep the image booted (only qcow2 supported right now)")

    args = parser.parse_args()
    search_path = args.image_search_path
    build_config_path = args.config
    keep = args.keep_booted

    testlib.boot_image(search_path, build_config_path, keep)


if __name__ == "__main__":
    main()
