#!/usr/bin/env python3
import argparse
import json
import os

import imgtestlib as testlib


def main():
    desc = "Build image for testing with boot-image"
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument("distro", type=str, default=None, help="distro for the image to boot test")
    parser.add_argument("image_type", type=str, default=None, help="type of the image to boot test")
    parser.add_argument("config", type=str, help="config used to build the image")
    parser.add_argument("--arch", default="", type=str, help="target arch of the image")

    args = parser.parse_args()
    distro = args.distro
    image_type = args.image_type
    config_path = args.config

    print(f"👷 Building image {distro}/{image_type} using config {config_path}")

    # print the config for logging
    with open(config_path, "r", encoding="utf-8") as config_file:
        config = json.load(config_file)
        print(json.dumps(config, indent=2))
        config_name = config["name"]

    testlib.runcmd(["go", "build", "-o", "./bin/build", "./cmd/build"])

    cmd = ["sudo", "-E", "./bin/build", "--output", "./build",
           "--distro", distro, "--type", image_type, "--config", config_path]
    arch = os.uname().machine
    if args.arch:
        arch = args.arch
        cmd += ["--arch", args.arch]
    testlib.runcmd_nc(cmd, extra_env=testlib.rng_seed_env())

    print("✅ Build finished!!")

    # Build artifacts are owned by root. Make them world accessible.
    testlib.runcmd(["sudo", "chmod", "a+rwX", "-R", "./build"])

    build_dir = os.path.join("build", testlib.gen_build_name(distro, arch, image_type, config_name))
    manifest_path = os.path.join(build_dir, "manifest.json")
    with open(manifest_path, "r", encoding="utf-8") as manifest_fp:
        manifest_data = json.load(manifest_fp)
    manifest_id = testlib.get_manifest_id(manifest_data)

    osbuild_ver, _ = testlib.runcmd(["osbuild", "--version"])

    distro_version = testlib.get_host_distro()
    osbuild_commit = testlib.get_osbuild_commit(distro_version)
    if osbuild_commit is None:
        osbuild_commit = "RELEASE"

    build_info = {
        "distro": distro,
        "arch": arch,
        "image-type": image_type,
        "config": config_name,
        "manifest-checksum": manifest_id,
        "osbuild-version": osbuild_ver.decode().strip(),
        "osbuild-commit": osbuild_commit,
        "commit": os.environ.get("CI_COMMIT_SHA", "N/A"),
        "runner-distro": distro_version,
    }
    testlib.write_build_info(build_dir, build_info)


if __name__ == "__main__":
    main()
