#!/usr/bin/env python3
#
# Create a job for each distro+arch to run test generators and triggers.
import sys

import imgtestlib as testlib

ARCHITECTURES = ["x86_64", "aarch64"]
MANIFEST_ONLY_ARCHES = ["ppc64le", "s390x"]
OSTREE_DISTROS = ["fedora", "rhel-8", "rhel-9", "centos-9"]


BASE_CONFIG = """---
stages:
  - init
  - build
  - ostree-build
  - finish

variables:
  GOPROXY: "https://proxy.golang.org,direct"

.base:
  before_script:
    - cat schutzbot/team_ssh_keys.txt |
        tee -a ~/.ssh/authorized_keys > /dev/null
  interruptible: true
  retry: 1
  tags:
    - terraform
  variables:
    PYTHONUNBUFFERED: 1

.terraform:
  extends: .base
  tags:
    - terraform

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish

fail:
  stage: finish
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh fail
    - exit 1  # make the pipeline fail so it doesn't look like success
  when: on_failure
"""

TEST_IMAGES_TEMPLATE = """
"test-images: [{distro}, {arch}]":
  stage: build
  extends: .terraform
  tags:
    - {tag}
  variables:
    RUNNER: {runner}-{arch}
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-manifests --distro {distro} --arch {arch}
  artifacts:
    paths:
      - {logdir}
"""

TEST_OSTREE_IMAGES_TEMPLATE = """
"test-ostree-images: [{distro}, {arch}]":
  stage: ostree-build
  extends: .terraform
  tags:
    - {tag}
  variables:
    RUNNER: {runner}-{arch}
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo -E ./test/scripts/install-dependencies
    - ./test/scripts/test-new-ostree-manifests --distro {distro} --arch {arch}
  needs:
    - "test-images: [{distro}, {arch}]"
  artifacts:
    paths:
      - {logdir}
"""

MANIFEST_GEN_TEMPLATE = """
"generate-manifests: [{distro}, {arch}]":
  stage: build
  extends: .terraform
  variables:
    RUNNER: {runner}-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches {arch} --distros {distro} --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"
"""


def sort_configs(configs):
    return sorted(configs, key=lambda img: img["distro"]+img["arch"]+img["image-type"])


def main():
    config_path = sys.argv[1]
    images = testlib.list_images(arches=ARCHITECTURES)
    combos = set()

    build_stage = []
    ostree_build_stage = []
    for img in sort_configs(images):
        combo = (img["distro"], img["arch"])
        if combo in combos:
            continue

        runner = testlib.get_ci_runner_for(img["distro"], img["arch"], "qcow2")
        tag = testlib.get_tag_for(runner)

        combos.add(combo)
        build_stage.append(TEST_IMAGES_TEMPLATE.format(
            distro=img["distro"],
            arch=img["arch"],
            runner=runner,
            tag=tag,
            logdir=testlib.BUILD_LOG_PATH))

        for ostree_distro_prefix in OSTREE_DISTROS:
            if img["distro"].startswith(ostree_distro_prefix):
                break
        else:
            continue

        ostree_build_stage.append(TEST_OSTREE_IMAGES_TEMPLATE.format(
            distro=img["distro"],
            arch=img["arch"],
            runner=runner,
            tag=tag,
            logdir=testlib.BUILD_LOG_PATH))

    man_only_images = testlib.list_images(arches=MANIFEST_ONLY_ARCHES)
    man_gen_stage = []
    for img in sort_configs(man_only_images):
        combo = (img["distro"], img["arch"])
        if combo in combos:
            continue

        combos.add(combo)
        runner = testlib.get_ci_runner_for(img["distro"], img["arch"], "qcow2")
        tag = testlib.get_tag_for(runner)
        man_gen_stage.append(MANIFEST_GEN_TEMPLATE.format(
            distro=img["distro"],
            arch=img["arch"],
            runner=runner,
            tag=tag))

    with open(config_path, "w", encoding="utf-8") as config_file:
        config_file.write(BASE_CONFIG)
        config_file.write("\n".join(build_stage))
        config_file.write("\n".join(ostree_build_stage))
        config_file.write("\n".join(man_gen_stage))


if __name__ == "__main__":
    main()
