#!/usr/bin/env python3
#
# Create a job for each distro+arch to run test generators and triggers.
import sys

import imgtestlib as testlib

ARCHITECTURES = ["x86_64", "aarch64"]
MANIFEST_ONLY_ARCHES = ["ppc64le", "s390x"]
RUNNER = testlib.testenv.get_common_ci_runner()
OSTREE_DISTROS = ["fedora", "rhel-8", "rhel-9", "centos-9"]


BASE_CONFIG = """---
stages:
  - init
  - gen
  - build
  - ostree-gen
  - ostree-build
  - verify
  - finish

variables:
  # Set the parent pipeline ID as a global variable so that the child pipeline
  # jobs can use it to retrieve artifacts.
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  GOPROXY: "https://proxy.golang.org,direct"

init:
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish

fail:
  stage: finish
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh fail
    - exit 1  # make the pipeline fail so it doesn't look like success
  when: on_failure
"""

GEN_TEMPLATE = """
"generate-build-config: [{distro}, {arch}]":
  stage: gen
  extends: .terraform
  variables:
    RUNNER: {runner}-{arch}
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - ./test/scripts/generate-build-config --distro {distro} --arch {arch} build-config.yml
  artifacts:
    paths:
      - build-config.yml
"""

TRIGGER_TEMPLATE = """
"image-build-trigger: [{distro}, {arch}]":
  stage: build
  trigger:
    include:
      - artifact: build-config.yml
        job: "generate-build-config: [{distro}, {arch}]"
    strategy: depend
  needs:
    - "generate-build-config: [{distro}, {arch}]"
"""

OSTREE_GEN_TEMPLATE = """
"generate-ostree-build-config: [{distro}, {arch}]":
  stage: ostree-gen
  extends: .terraform
  variables:
    RUNNER: {runner}-{arch}
    INTERNAL_NETWORK: "true"
  script:
    - sudo -E ./test/scripts/setup-osbuild-repo
    - sudo ./test/scripts/install-dependencies
    - ./test/scripts/generate-ostree-build-config --distro {distro} --arch {arch} build-config.yml build-configs
  artifacts:
    paths:
      - build-config.yml
      - build-configs
  needs:
    - "image-build-trigger: [{distro}, {arch}]"
"""

OSTREE_TRIGGER_TEMPLATE = """
"image-build-ostree-trigger: [{distro}, {arch}]":
  stage: ostree-build
  trigger:
    include:
      - artifact: build-config.yml
        job: "generate-ostree-build-config: [{distro}, {arch}]"
    strategy: depend
  needs:
    - "generate-ostree-build-config: [{distro}, {arch}]"
"""


MANIFEST_GEN_TEMPLATE = """
"generate-manifests: [{distro}, {arch}]":
  stage: gen
  extends: .terraform
  variables:
    RUNNER: {runner}-x86_64
    INTERNAL_NETWORK: "true"
  script: |
    sudo -E ./test/scripts/setup-osbuild-repo
    sudo ./test/scripts/install-dependencies
    echo "GOPROXY=$GOPROXY"
    go run ./cmd/gen-manifests --arches {arch} --distros {distro} --workers 10 --metadata=false --output ./manifests
    errors=0
    for manifest in ./manifests/*; do
      if osbuild --inspect $manifest > output; then
        echo "$manifest OK";
      else
        echo "$manifest validation failed";
        cat output;
        errors+=1
      fi;
    done
    exit "$errors"
"""

BOOTC_IMAGE_BUILDER_TEMPLATE = """
"bootc-image-builder/test-build-disk [{arch}]":
  stage: gen
  extends: .terraform
  variables:
    RUNNER: {runner}-{arch}
  rules:
    # 1. Skip the job if we're on the github merge queue
    - if: '$CI_COMMIT_BRANCH =~ /^gh-readonly-queue/'
      when: never
    # 2. Fallback rule for any other branch name
    - if: '$CI_COMMIT_BRANCH'
  script:
    - sudo ./test/scripts/install-dependencies
    - sudo mkdir -pv /var/tmp/bootc-image-builder-tests
    - sudo -E XDG_RUNTIME_DIR= PYTHONPATH=. pytest -vv --setup-show --basetemp=/var/tmp/bootc-image-builder-tests ./bootc-image-builder/test/test_build_disk.py

"bootc-image-builder/test-manifest [{arch}]":
  stage: gen
  extends: .terraform
  variables:
    RUNNER: {runner}-{arch}
  rules:
    # 1. Skip the job if we're on the github merge queue
    - if: '$CI_COMMIT_BRANCH =~ /^gh-readonly-queue/'
      when: never
    # 2. Fallback rule for any other branch name
    - if: '$CI_COMMIT_BRANCH'
  script:
    - sudo ./test/scripts/install-dependencies
    - sudo mkdir -pv /var/tmp/bootc-image-builder-tests
    - sudo -E XDG_RUNTIME_DIR= PYTHONPATH=. pytest -vv --setup-show --basetemp=/var/tmp/bootc-image-builder-tests ./bootc-image-builder/test/test_manifest.py

"bootc-image-builder/test-opts-and-progress [{arch}]":
  stage: gen
  extends: .terraform
  variables:
    RUNNER: {runner}-{arch}
  rules:
    # 1. Skip the job if we're on the github merge queue
    - if: '$CI_COMMIT_BRANCH =~ /^gh-readonly-queue/'
      when: never
    # 2. Fallback rule for any other branch name
    - if: '$CI_COMMIT_BRANCH'
  script:
    - sudo ./test/scripts/install-dependencies
    - sudo mkdir -pv /var/tmp/bootc-image-builder-tests
    - sudo -E XDG_RUNTIME_DIR= PYTHONPATH=. pytest -vv --setup-show --basetemp=/var/tmp/bootc-image-builder-tests ./bootc-image-builder/test/test_opts.py ./bootc-image-builder/test/test_progress.py
"""


def sort_configs(configs):
    return sorted(configs, key=lambda img: img["distro"]+img["arch"]+img["image-type"])


def main():
    config_path = sys.argv[1]
    images = testlib.core.list_images(arches=ARCHITECTURES)
    combos = set()

    gen_stage = []
    trigger_stage = []
    ostree_gen_stage = []
    ostree_trigger_stage = []
    for img in sort_configs(images):
        combo = (img["distro"], img["arch"])
        if combo in combos:
            continue

        combos.add(combo)
        gen_stage.append(GEN_TEMPLATE.format(
            distro=img["distro"],
            arch=img["arch"],
            runner=RUNNER))

        trigger_stage.append(TRIGGER_TEMPLATE.format(
            distro=img["distro"],
            arch=img["arch"],
            runner=RUNNER))

        for ostree_distro_prefix in OSTREE_DISTROS:
            if img["distro"].startswith(ostree_distro_prefix):
                break
        else:
            continue

        ostree_gen_stage.append(OSTREE_GEN_TEMPLATE.format(
            distro=img["distro"],
            arch=img["arch"],
            runner=RUNNER))

        ostree_trigger_stage.append(OSTREE_TRIGGER_TEMPLATE.format(
            distro=img["distro"],
            arch=img["arch"],
            runner=RUNNER))

    man_only_images = testlib.core.list_images(arches=MANIFEST_ONLY_ARCHES)
    man_gen_stage = []
    for img in sort_configs(man_only_images):
        combo = (img["distro"], img["arch"])
        if combo in combos:
            continue

        combos.add(combo)
        man_gen_stage.append(MANIFEST_GEN_TEMPLATE.format(distro=img["distro"], arch=img["arch"], runner=RUNNER))

    # Run bootc-image-builder tests on Fedora 44 only for now (both arches)
    for arch in ("x86_64", "aarch64"):
        trigger_stage.append(BOOTC_IMAGE_BUILDER_TEMPLATE.format(
            runner=RUNNER,
            arch=arch,
        ))

    with open(config_path, "w", encoding="utf-8") as config_file:
        config_file.write(BASE_CONFIG.format(runner=RUNNER))
        config_file.write(testlib.core.BASE_CONFIG)
        config_file.write("\n".join(gen_stage))
        config_file.write("\n".join(trigger_stage))
        config_file.write("\n".join(ostree_gen_stage))
        config_file.write("\n".join(ostree_trigger_stage))
        config_file.write("\n".join(man_gen_stage))


if __name__ == "__main__":
    main()
