#!/usr/bin/env bash

set -e

# we need qemu-kvm here but libvirt-devel pulls this in

install_deps() {
    dnf -y install \
        awscli2 \
        btrfs-progs-devel \
        cloud-utils \
        device-mapper-devel \
        flake8 \
        gcc \
        go \
        gpgme-devel \
        krb5-devel \
        libvirt-devel \
        lorax \
        osbuild \
        osbuild-depsolve-dnf \
        osbuild-luks2 \
        osbuild-lvm2 \
        osbuild-ostree \
        osbuild-selinux \
        podman \
        pylint \
        python3 \
        python3-boto3 \
        python3-pip \
        python3-pytest \
        python3-qemu-qmp \
        python3-scp \
        xz \
        yamllint
}

install_deps_el() {
    dnf -y install \
        awscli2 \
        device-mapper-devel \
        gcc \
        go \
        gpgme-devel \
        krb5-devel \
        libvirt-devel \
        lorax \
        osbuild \
        osbuild-depsolve-dnf \
        osbuild-luks2 \
        osbuild-lvm2 \
        osbuild-ostree \
        osbuild-selinux \
        podman \
        python3 \
        python3-pip \
        python3-pytest \
        xz
}

source /etc/os-release
case "${ID}" in
    "centos" | "rhel")
        install_deps_el
        ;;
    *)
        install_deps
        ;;
esac
