---
name: "Updates Go dependencies via gobump"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # Every Sunday at 15:00
    - cron: "0 15 * * 0"

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:43
    steps:
      - name: Prepare environment and run tests
        run: |
          set -xe
          sudo dnf -y install git gh golang skopeo libvirt-devel gpgme-devel btrfs-progs-devel krb5-devel
          git clone --depth 1 https://github.com/osbuild/images
          cd images/
          go build ./...
          go test ./...

      - name: Run gobump and open a PR
        env:
          GH_TOKEN: ${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}
        run: |
          set -xe
          cd images/
          git config user.name "schutzbot"
          git config user.email "schutzbot@gmail.com"
          branch="schutz-gobump-$(date -I)"
          git checkout -b "${branch}"
          go run github.com/lzap/gobump@latest \
            -exec "go build ./..." \
            -exec "go test ./..." \
            -exec "./tools/prepare-source.sh" \
            -exec "./tools/gen-manifest-checksums.sh" \
            -verbose -format markdown | tee "/tmp/github_pr_body.txt"
          git log --oneline "main..${branch}"
          git push -f "https://$GH_TOKEN@github.com/schutzbot/images.git" "${branch}"
          gh pr create \
            -t "Update dependencies $(date -I)" \
            -F "/tmp/github_pr_body.txt" \
            --repo "osbuild/images" \
            --base "main" \
            --head "schutzbot:${branch}"
