---
name: Tests

# NOTE(mhayden): Restricting branches prevents jobs from being doubled since
# a push to a pull request triggers two events.
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  # for merge queue
  merge_group:

jobs:
  unit-tests-fedora:
    strategy:
      matrix:
        fedora_version:
          - name: previous
            version: 42
          - name: current
            version: 43
            # Enable this when we get osbuild rpm builds for Fedora 44
            # - name: rawhide
            #   version: rawhide
            #   continue-on-error: true
      fail-fast: false  # if one fails, keep the other(s) running
    name: "🛃 Unit tests (Fedora ${{ matrix.fedora_version.name }})"
    runs-on: ubuntu-24.04
    container: registry.fedoraproject.org/fedora:${{ matrix.fedora_version.version }}
    continue-on-error: ${{ matrix.continue-on-error || false }}
    env:
      # workaround for expired cert at source of indirect dependency
      # (go.opencensus.io/trace)
      GOPROXY: "https://proxy.golang.org|direct"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          set-safe-directory: true

      - name: Install python3
        # The Fedora container doesn't have python3 installed by default
        run: dnf -y install python3

      - name: Set up repository for pinned osbuild commit
        run: ./test/scripts/setup-osbuild-repo

      - name: Install test dependencies
        run: ./test/scripts/install-dependencies

      - name: Mark the working directory as safe for git
        run: git config --global --add safe.directory "$(pwd)"

      - name: Run unit tests
        # skip the TestResolverLocalManifest and
        # TestBlockingResolverLocalManifest tests. They are tested separately
        # (see below: requires root)
        run: go test  -race -timeout 20m ./... -test.skip 'TestBlockingResolverLocalManifest|TestResolverLocalManifest'

      - name: Run depsolver tests with force-dnf to make sure it's not skipped
        run: go test -race ./pkg/depsolvednf/... -force-dnf

  container-resolver-tests:
    name: "🛃 Container resolver tests"
    runs-on: ubuntu-24.04
    env:
      # workaround for expired cert at source of indirect dependency
      # (go.opencensus.io/trace)
      GOPROXY: "https://proxy.golang.org|direct"

    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.12"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          set-safe-directory: true

      - name: Apt update
        run: sudo apt update

      # This is needed for the container resolver dependencies
      - &apt_install_dependencies
        name: Install libgpgme devel package
        run: sudo apt install -y libgpgme-dev libbtrfs-dev libdevmapper-dev podman

      # We need to run the test as root, since we use the root
      # containers-storage for the local resolvers
      - name: Run unit tests for container resolve
        run: sudo go test ./pkg/container/... --force-local-resolver

      - name: Run unit tests for bib container
        run: sudo go test ./pkg/bootc/... --fail-if-podman-missing

      - name: Run tests for bootc container
        run: sudo go test ./pkg/distro/bootc/... ./pkg/distro/generic/...

  unit-tests-cs:
    strategy:
      matrix:
        centos_stream:
          - version: 9
            image_tag: stream9
          - version: 10
            image_tag: stream10
      fail-fast: false  # if one fails, keep the other(s) running
    name: "🛃 Unit tests (CentOS Stream ${{ matrix.centos_stream.version }})"
    runs-on: ubuntu-24.04
    container:
      image: quay.io/centos/centos:${{ matrix.centos_stream.image_tag }}
    env:
      GOFLAGS: "-tags=exclude_graphdriver_btrfs"
      # workaround for expired cert at source of indirect dependency
      # (go.opencensus.io/trace)
      GOPROXY: "https://proxy.golang.org|direct"

    steps:
      - name: Install dnf plugins
        run: dnf -y install dnf-plugins-core

      - name: Enable crb repo
        run: dnf config-manager --set-enabled crb

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          set-safe-directory: true

      - name: Set up repository for pinned osbuild commit
        run: ./test/scripts/setup-osbuild-repo

      - name: Install build and test dependencies
        run: dnf -y install krb5-devel libvirt-devel gcc git-core go gpgme-devel osbuild-depsolve-dnf device-mapper-devel

      - name: Mark the working directory as safe for git
        run: git config --global --add safe.directory "$(pwd)"

      - name: Install openssl for cgo test below
        run: dnf -y install openssl

      - name: Run unit tests
        run: make test

  lint:
    name: "⌨ Lint"
    runs-on: ubuntu-24.04
    env:
      # workaround for expired cert at source of indirect dependency
      # (go.opencensus.io/trace)
      GOPROXY: "https://proxy.golang.org|direct"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.12"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          set-safe-directory: true

      - name: Apt update
        run: sudo apt update

      # This is needed to lint internal/upload/koji package
      - name: Install kerberos devel package
        run: sudo apt install -y libkrb5-dev

      # This is needed to lint pkg/cloud/libvirt package
      - name: Install libvirt devel package
        run: sudo apt install -y libvirt-dev

      # This is needed for the container upload dependencies
      - *apt_install_dependencies

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.8
          args: --verbose --timeout 5m0s

  shellcheck:
    name: "🐚 Shellcheck"
    runs-on: ubuntu-24.04
    env:
      # workaround for expired cert at source of indirect dependency
      # (go.opencensus.io/trace)
      GOPROXY: "https://proxy.golang.org|direct"
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          set-safe-directory: true
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          ignore: vendor  # We don't want to fix the code in vendored dependencies
        env:
          # don't check /etc/os-release sourcing, allow useless cats to live inside our codebase, and
          # allow seemingly unreachable commands
          SHELLCHECK_OPTS: -e SC1091 -e SC2002 -e SC2317

  python-test:
    name: "🐍 pytest (imgtestlib and test scripts)"
    runs-on: ubuntu-24.04
    env:
      # workaround for expired cert at source of indirect dependency
      # (go.opencensus.io/trace)
      GOPROXY: "https://proxy.golang.org|direct"
    container:
      image: registry.fedoraproject.org/fedora:latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          set-safe-directory: true

      - name: Install build and test dependencies
        run: ./test/scripts/install-dependencies

      - name: Testing imgtestlib and test scripts
        run: |
          python3 -m pytest -v -k "not images_integration"

  python-lint:
    name: "🐍 Lint (test scripts)"
    runs-on: ubuntu-24.04
    env:
      # workaround for expired cert at source of indirect dependency
      # (go.opencensus.io/trace)
      GOPROXY: "https://proxy.golang.org|direct"
    container:
      image: registry.fedoraproject.org/fedora:latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          set-safe-directory: true

      - name: Install build and test dependencies
        run: |
          ./test/scripts/install-dependencies
          dnf -y install python3-pylint

      - name: Analysing the code with pylint
        run: |
          python3 -m pylint --version
          python3 -m pylint $(grep -l "/usr/bin/env python3" -r test/scripts) test/scripts/*.py

  yaml-checks:
    name: "YAML checks"
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          set-safe-directory: true

      - name: Install checkers
        run: |
          sudo apt update
          sudo apt install -y yamllint yq

      - name: YAML Lint
        run: |
          find . "(" -iname "*.yaml" -or -iname "*.yml" ")" -exec yamllint --strict {} \+

      - name: Check YAML definitions with yq
        # yq will catch issues that yamllint will not, like duplicate anchros
        run: |
          find . "(" -iname "*.yaml" -or -iname "*.yml" ")" -exec yq . {} \+ > /dev/null

  cross-arch-integration-test:
    strategy:
      matrix:
        arch:
          - ppc64le
          - s390x
      fail-fast: false  # if one fails, keep the other(s) running
    name: "Cross-arch qemu based image build/boot smoke test"
    runs-on: ubuntu-24.04
    env:
      # workaround for expired cert at source of indirect dependency
      # (go.opencensus.io/trace)
      GOPROXY: "https://proxy.golang.org|direct"
      GOFLAGS: "-buildvcs=false"
    container:
      image: registry.fedoraproject.org/fedora:latest
      options: "--privileged"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          set-safe-directory: true

      - name: Install python3
        # The Fedora container doesn't have python3 installed by default
        run: dnf -y install python3

      - name: Setup repository for pinned osbuild commit
        run: ./test/scripts/setup-osbuild-repo

      - name: Install osbuild dependencies
        run: dnf -y install osbuild osbuild-depsolve-dnf

      - name: Install build and test dependencies
        run: ./test/scripts/install-dependencies

      - name: Manually start qemu-user-static
        run: |
          # mostly for debugging
          mount | grep binfmt_misc || true
          ls /proc/sys/fs/binfmt_misc/
          sudo mount -t binfmt_misc none /proc/sys/fs/binfmt_misc
          ls /proc/sys/fs/binfmt_misc/
          sudo SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-binfmt
          ls /proc/sys/fs/binfmt_misc/
          sudo SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-binfmt /usr/lib/binfmt.d/qemu-*.conf
          ls /proc/sys/fs/binfmt_misc/

      - name: Cross arch integration test
        run: |
          sudo -E pytest -rs -k ${{ matrix.arch }} -s -v ./test/test_cross_arch_integration.py
