---
name: Tests

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  apt-update:
    name: "Apt update - nothing else"
    runs-on: ubuntu-24.04
    steps:
      - name: Apt update
        run: sudo apt update
